type Product {
  id: Int!
  itemName: String!
  authorLink: String
  authorName: String
  imageCredit: String
  imageSrc: String!
  price: Float!
  category_level0: String
  description: String!
  category_level1: String
}

type PurchaseDetail {
  items: [PurchaseItemDetail!]
  deliveryDate: String!
}

type PurchaseItemDetail {
  itemName: String!,
  quantity: Int!,
  price: Float!
}

type InfoQueryType {
  subtypes: [String]
  products: [Product]
}

type Query {
  info(subtypes: [String], itemName: String, sortType: String, min: Float, max: Float, name: String, showAmt: Int): InfoQueryType,
  purchase(orderId: String!, email: String!) : PurchaseDetail!
}

type Mutation {
  addPurchase(orderId: String!, email: String!): Boolean!,
  seed: Boolean!
}